In [2]:
fecha = str(input("ingrese una fecha en formato dd/mm/aa :"))

ingrese una fecha en formato dd/mm/aa : 26/08/24


In [8]:
fecha[:2]*2

'2626'

In [34]:
t = []
tini = 1
tfin = 10
h = 0.1
n = int((tfin-tini)/h)
t.append(tini)
for i in range(n):
    t.append(t[i]+h)

print(t)
    


[1, 1.1, 1.2000000000000002, 1.3000000000000003, 1.4000000000000004, 1.5000000000000004, 1.6000000000000005, 1.7000000000000006, 1.8000000000000007, 1.9000000000000008, 2.000000000000001, 2.100000000000001, 2.200000000000001, 2.300000000000001, 2.4000000000000012, 2.5000000000000013, 2.6000000000000014, 2.7000000000000015, 2.8000000000000016, 2.9000000000000017, 3.0000000000000018, 3.100000000000002, 3.200000000000002, 3.300000000000002, 3.400000000000002, 3.500000000000002, 3.6000000000000023, 3.7000000000000024, 3.8000000000000025, 3.9000000000000026, 4.000000000000003, 4.100000000000002, 4.200000000000002, 4.300000000000002, 4.400000000000001, 4.500000000000001, 4.6000000000000005, 4.7, 4.8, 4.8999999999999995, 4.999999999999999, 5.099999999999999, 5.199999999999998, 5.299999999999998, 5.399999999999998, 5.499999999999997, 5.599999999999997, 5.699999999999997, 5.799999999999996, 5.899999999999996, 5.999999999999996, 6.099999999999995, 6.199999999999995, 6.2999999999999945, 6.3999999

In [37]:
l = [1, 5, 9, 8, 7, 6, 14]
for i in l:
    if i%2:
        continue
    print(i, " es par")

8  es par
6  es par
14  es par


In [54]:
x = 10
for i in range(2,x):
    if x%i == 0:
        print(x, " no es primo")
        break
else:
    print(x, " es primo")
    
    

10  no es primo


In [85]:
import math

tol = 0.01
error = 1
x = 2
sum = 0
n = 0
sum = x**n/math.factorial(n)
while error > tol:
    n = n + 1
    val_ant = sum
    sum = sum + x**n/math.factorial(n)
    val_nuevo = sum
    error = abs((val_nuevo-val_ant)/val_nuevo)

print(val_nuevo)
    
    
    

7.3809523809523805


In [83]:
math.exp(2)

7.38905609893065

In [90]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [94]:
a.size

6

In [96]:
a.dtype

dtype('int32')

In [98]:
b = np.ones([2,3])

In [100]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:
a + b

array([[2., 3., 4.],
       [5., 6., 7.]])

In [106]:
np.empty(5)


array([0.00000000e+000, 6.02784390e-312, 6.02784391e-312, 6.02784390e-312,
       3.69126375e-317])

In [108]:
a[0][3]=5

IndexError: index 3 is out of bounds for axis 0 with size 3

In [120]:
a>3

array([[False, False, False],
       [ True,  True,  True]])

In [122]:
print(a[a>3])

[4 5 6]


In [124]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [136]:
c = np.ones((2,2))

In [138]:
c

array([[1., 1.],
       [1., 1.]])

In [140]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
a*c

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [144]:
a@c

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [146]:
c@a

array([[5., 7., 9.],
       [5., 7., 9.]])

In [179]:
x = np.array([5, 9, 25])
y = np.array([[6],[3],[1]])

In [181]:
x.shape

(3,)

In [183]:
y.shape

(3, 1)

In [185]:
x*y

array([[ 30,  54, 150],
       [ 15,  27,  75],
       [  5,   9,  25]])

In [189]:
x @ y

array([82])

In [172]:
x+y

array([[11, 15, 31],
       [ 8, 12, 28],
       [ 6, 10, 26]])

In [174]:
x

array([[ 5,  9, 25]])

In [176]:
y

array([[6],
       [3],
       [1]])

In [192]:
z = y

In [194]:
z[0]=500

In [196]:
y

array([[500],
       [  3],
       [  1]])

In [208]:
w = y.copy()

In [210]:
w

array([[500],
       [  3],
       [  1]])

In [212]:
w[0]=1

In [214]:
w

array([[1],
       [3],
       [1]])

In [216]:
y

array([[500],
       [  3],
       [  1]])